set foreign_key_checks = 0;
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.INGREDIENT; 
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.MENU;
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.NUTRITION;
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.ORDERING;
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.ORDERING_ITEM;       
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.RECIPE;        
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.RECIPE_INGREDIENT; 
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.STOCK;             
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.SUPPLIER;          
DROP TABLE SOONGSIL_STUDENT_CAFETERIA_SCM.SUPPLIER_CONTRACT;
set foreign_key_checks = 1;

DROP USER 'kitchen_staff'@'%', 'purchasing_manager'@'%', 'supplier'@'%', 'nutritionist'@'%';
FLUSH PRIVILEGES;
